### ISSUE TITLE
QUESTION: What branch to merge into for v6 patches?

### ISSUE THREAD

**Issue by AndrewGibson27** [npm/ssri#18]
# What / Why
It looks like this project has a base branch for `v7` but not `v6`.  What branch should we merge into for `v6` patches? I've got a [branch](https://github.com/AndrewGibson27/ssri/tree/v6-fix-regex) going to port [this fix](https://github.com/npm/ssri/commit/76e223317d971f19e4db8191865bdad5edee40d2) into what I hope will be `v6.0.2` (needed for Webpack 4 support).

**Comment by keepitterron** [comment]
heavy plus one on this.
we depend on webpack 4 and there is no other way left to have this vulnerability fixed 🙏 

thanks @AndrewGibson27 !

**Comment by pedelman** [comment]
@isaacs @nlf I was wondering if anyone has seen this question. It seems this is best path forward to resolve CVE in webpack v4 based on discussion in this related issue: https://github.com/webpack-contrib/terser-webpack-plugin/issues/388. 

If you could provide some next steps / guidance on how to proceed, it would be much appreciated. 

Thanks for the help!

**Comment by nlf** [comment]
backported and landed as v6.0.2

**Comment by stefanetoh** [comment]
> backported and landed as v6.0.2

Nice! 

But.. how come `v6.0.2` isn't listed as a patched version: https://github.com/advisories/GHSA-vx3p-948g-6vhq? Shouldn't it be? 🤔

**Comment by pedelman** [comment]
@stefanetoh I sent a note to NIST, NPM, and GitHub support. Im hopeful it can be resolved in the coming days. For my projects, I have already updated to 6.0.2 and manually dismissed the dependabot alert.

Its not really a clear process for communicating this fix. If anyone has contacts in this area, please reach out and inform them so users can update appropriately.

**Comment by nlf** [comment]
yeah, we have to wait for all of the various advisory databases to update their advisories in order for all of the alerts to totally clear up. we'll see what we can do to speed that process up.

**Comment by stefanetoh** [comment]
@pedelman @nlf - aah, ok - then i know :D thanks for the info 🌟
