### ISSUE TITLE
npm install ssri - EINTEGRITY error

### ISSUE THREAD

**Issue by chrisschaub** [npm/ssri#7]
Trying to install ssri, gets EINTEGRITY ERROR. Node 6.17.1

% npm install ssri

verbose stack Error: sha1-mBrhQVufs3KuFfEVbV0yt9zHi90= integrity checksum failed when using sha1: wanted sha1-mBrhQVufs3KuFfEVbV0yt9zHi90= but got sha512-fFUdiIir8CBx5sEToEQKRfodXXB9FaIY3G8EObFovG01iN8iLSqELh1f2gYaCmnmilDFYvXWsG7YqbBfo3u/cg== sha1-1mJPy4IQpFl4civGKyIUYHaCHW8=. (16984 bytes)

Tried to clear caches for npm and nvm, no luck.

**Comment by Beauceron** [comment]
@chrisschaub I have the same issue do you remember how you fix this?
